module.exports = {
  theme: {
    // Add/remove as needed to control dist size.
    screens: {
      xs: '556px',
      sm: '756px',
      md: '992px',
      lg: '1200px',
      xl: '1500px'
    },
    // Use flex for column widths.
    flex: {
      '1': '0 0 100%',
      '1/2': '0 0 50%',
      '1/3': '0 0 33.3%',
      '1/4': '0 0 25%',
      '2/3': '0 0 66.6%',
      '3/4': '0 0 75%',
    },
    // Apply margin and padding for gutter widths.
    margin: {
      '-4': '-4px',
      '-8': '-8px',
      '-12': '-12px',
      '-16': '-16px'
    },
    padding: {
      '4': '4px',
      '8': '8px',
      '12': '12px',
      '16': '16px'
    },
    colors: {},
    spacing: {},
    backgroundColor: theme => theme('colors'),
    backgroundPosition: {},
    backgroundSize: {},
    borderColor: theme => ('colors'),
    borderRadius: {},
    borderWidth: {},
    boxShadow: {},
    container: {},
    cursor: {},
    fill: {},
    flexGrow: {},
    flexShrink: {},
    fontFamily: {
      sans: [],
      serif: [],
      mono: [],
    },
    fontSize: {},
    fontWeight: {},
    height: {},
    inset: {},
    letterSpacing: {},
    lineHeight: {},
    listStyleType: {},
    maxHeight: {},
    maxWidth: {},
    minHeight: {},
    minWidth: {},
    objectPosition: {},
    opacity: {},
    order: {},

    placeholderColor: {},
    stroke: {},
    textColor: {},
    width: {},
    zIndex: {},
  },
  variants: {
    accessibility: [],
    alignContent: [],
    alignItems: [],
    alignSelf: [],
    appearance: [],
    backgroundAttachment: [],
    backgroundColor: [],
    backgroundPosition: [],
    backgroundRepeat: [],
    backgroundSize: [],
    borderCollapse: [],
    borderColor: [],
    borderRadius: [],
    borderStyle: [],
    borderWidth: [],
    boxShadow: [],
    cursor: [],
    display: ['responsive'],
    fill: [],
    flex: ['responsive'],
    flexDirection: [],
    flexGrow: [],
    flexShrink: [],
    flexWrap: [],
    float: [],
    fontFamily: [],
    fontSize: [],
    fontSmoothing: [],
    fontStyle: [],
    fontWeight: [],
    height: [],
    inset: [],
    justifyContent: [],
    letterSpacing: [],
    lineHeight: [],
    listStylePosition: [],
    listStyleType: [],
    margin: ['responsive'],
    maxHeight: [],
    maxWidth: [],
    minHeight: [],
    minWidth: [],
    objectFit: [],
    objectPosition: [],
    opacity: [],
    order: [],
    outline: [],
    overflow: [],
    padding: ['responsive'],
    placeholderColor: [],
    pointerEvents: [],
    position: [],
    resize: [],
    stroke: [],
    tableLayout: [],
    textAlign: [],
    textColor: [],
    textDecoration: [],
    textTransform: [],
    userSelect: [],
    verticalAlign: [],
    visibility: [],
    whitespace: [],
    width: [],
    wordBreak: [],
    zIndex: [],
  },
  corePlugins: {},
  plugins: [],
}
