module.exports = {
  theme: {
    // Add/remove as needed to control dist size.
    screens: {
      sm: '756px',
      md: '992px',
      lg: '1200px',
    },
    // Apply margin and padding for gutter widths.
    margin: {
      '-15': '-15px',
      'auto': 'auto',
    },
    padding: {
      '15': '15px',
    },
    // Width for columns and containers.
    width: {
      '1/4': '25%',
      '1/3': '33.3%',
      '1/2': '50%',
      '2/3': '66.6%',
      '3/4': '75%',
      '1/1': '100%',
      '800': '800px',
      '1100': '1100px',
    },
    maxWidth: {
      'full': '100%',
    },
    colors: {},
    spacing: {},
    backgroundColor: (theme) => theme('colors'),
    backgroundPosition: {},
    backgroundSize: {},
    borderColor: (theme) => theme('colors'),
    borderRadius: {},
    borderWidth: {},
    boxShadow: {},
    container: {},
    cursor: {},
    fill: {},
    flex: {},
    flexGrow: {},
    flexShrink: {},
    fontFamily: {},
    fontSize: {},
    fontWeight: {},
    height: {},
    inset: {},
    letterSpacing: {},
    lineHeight: {},
    listStyleType: {},
    maxHeight: {},
    minHeight: {},
    minWidth: {},
    objectPosition: {},
    opacity: {},
    order: {},
    placeholderColor: {},
    stroke: {},
    textColor: {},
    zIndex: {},
  },
  variants: {
    accessibility: [],
    alignContent: [],
    alignItems: [],
    alignSelf: [],
    appearance: [],
    backgroundAttachment: [],
    backgroundColor: [],
    backgroundPosition: [],
    backgroundRepeat: [],
    backgroundSize: [],
    borderCollapse: [],
    borderColor: [],
    borderRadius: [],
    borderStyle: [],
    borderWidth: [],
    boxShadow: [],
    cursor: [],
    display: ['responsive'],
    fill: [],
    flex: ['responsive'],
    flexDirection: [],
    flexGrow: [],
    flexShrink: [],
    flexWrap: [],
    float: [],
    fontFamily: [],
    fontSize: [],
    fontSmoothing: [],
    fontStyle: [],
    fontWeight: [],
    height: [],
    inset: [],
    justifyContent: [],
    letterSpacing: [],
    lineHeight: [],
    listStylePosition: [],
    listStyleType: [],
    margin: ['responsive'],
    maxHeight: [],
    maxWidth: [],
    minHeight: [],
    minWidth: [],
    objectFit: [],
    objectPosition: [],
    opacity: [],
    order: [],
    outline: [],
    overflow: [],
    padding: ['responsive'],
    placeholderColor: [],
    pointerEvents: [],
    position: [],
    resize: [],
    stroke: [],
    tableLayout: [],
    textAlign: [],
    textColor: [],
    textDecoration: [],
    textTransform: [],
    userSelect: [],
    verticalAlign: [],
    visibility: [],
    whitespace: [],
    width: ['responsive'],
    wordBreak: [],
    zIndex: [],
  },
  corePlugins: {},
  plugins: [],
};
